# Generated by Django 4.2.3 on 2024-02-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(blank=True, default='RUB', max_length=10, null=True, verbose_name='валюта'),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_paid',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='статус оплаты'),
        ),
        migrations.AddField(
            model_name='payment',
            name='session_id',
            field=models.TextField(blank=True, null=True, verbose_name='id сессии'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay_method',
            field=models.IntegerField(blank=True, choices=[(1, 'Cash'), (2, 'Card')], null=True, verbose_name='Способ оплаты'),
        ),
    ]
