# Generated by Django 4.2.3 on 2024-02-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_payment_currency_payment_is_paid_payment_session_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pay_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Card')], max_length=10, null=True, verbose_name='Способ оплаты'),
        ),
    ]
