# Generated by Django 4.2.3 on 2024-03-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_payment_pay_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='last_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата последнего обновления'),
        ),
        migrations.AddField(
            model_name='course',
            name='last_view',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
